### ISSUE TITLE
New version release

### ISSUE THREAD

**Issue by szlin** [imZack/modem-cmd#1]
Hi Zack,

Could you release new version of modem-cmd, hence I can upload it into Debian archive.

Thanks.

SZ Lin

**Comment by imZack** [comment]
1.0.0 49d196f8b3d0e9af06f63de2bf7ec540098c903c has been released!

**Comment by szlin** [comment]
@imZack  Please release version in https://github.com/imZack/modem-cmd/releases

**Comment by szlin** [comment]
@imZack  Please release version in https://github.com/imZack/modem-cmd/releases

**Comment by imZack** [comment]
@szlin https://github.com/imZack/modem-cmd/releases/tag/v1.0.0
